gui:
  nerdFontsVersion: "3"

git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never

customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
