gui:
  nerdFontsVersion: "3"
git:
  diffContextSize: 6
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
customCommands:
  - key: "C"
    command: "czg"
    description: "commit with czg"
    context: "files"
    loadingText: "opening czg commit tool"
    output: terminal
