env NVIM_THEME="vaporgual"
env ZSH_UNKNOWN_TOKEN_STYLE=fg=1

background_image ./wallpapers/1.png
background_tint 0.98

font_family      VictorMono Nerd Font
bold_font        Victor Mono Bold
italic_font      Victor Mono Italic
bold_italic_font Victor Mono Bold Italic

# vaporgual - neon/cyberpunk theme
background            #0d0d14
foreground            #e8e8f0

cursor       #f7ff00
cursor_text_color #000000
# cursor                #00f0ff
# cursor_text_color     #0d0d14

selection_background  #252530
selection_foreground  #e8e8f0

# black
color0       #121218
color8       #6a6a7a

# red
color1       #ff073a
color9       #ff2a6d

# green
color2       #01ff88
color10      #01ff88

# yellow / orange
color3       #ff5c00
color11      #f9f002

# blue (path)
color4       #00f0ff
color12      #c8a8ff

# magenta (username)
color5       #ff00aa
color13      #ff00aa

# cyan
color6       #f9f002
color14      #00b8b8

# white
color7       #a0a0b0
color15      #e8e8f0
