plugins=(git)

ZSH_THEME=leite
source ~/.oh-my-zsh/oh-my-zsh.sh

export EDITOR="nvim"
export VISUAL="nvim"

# pnpm
export PNPM_HOME="$HOME/.pnpm-home"
export PATH="$PNPM_HOME:$PATH"

export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$PATH"

export BUN_INSTALL=$HOME/.bun
export PATH=$BUN_INSTALL/bin:$PATH

# pipx
export PATH=/Users/wallpants/.local/bin:$PATH

# vim keymaps
set -o vi

# ALIAS
alias python="python3"
alias vi="nvim"
alias vim="vim"
alias lzg="lazygit"
alias :q="exit"
alias :Q="exit"
alias dotfiles="cd ~/.dotfiles"
alias public="cat ~/.ssh/id_ed25519.pub"
alias ssh="nohup lemonade server > /dev/null 2>&1 &! kitty +kitten ssh -R 2489:127.0.0.1:2489"
alias l="ls -1"
alias la="ls -oAh"

# remap Ctrl+L to both scroll the current screen contents into the scrollback buffer
# and clear the screen, instead of just clearing the screen
scroll-and-clear-screen() {
    printf '\n%.0s' {1..$LINES}
    zle clear-screen
}
zle -N scroll-and-clear-screen
bindkey '^L' scroll-and-clear-screen
bindkey "^N" down-line-or-beginning-search
bindkey "^P" up-line-or-beginning-search

echo ""
echo ""
echo "Microsoft(R) Windows 95"
echo "   (C)Copyright Microsoft Corp 1981-1996."
echo ""

source ~/.dotfiles/zsh/os_specific.zsh

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/wallpants/.lmstudio/bin"
